// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYGpigGFsYh8hfUfQvSSCuE-lRQRGF_D0',
    appId: '1:275825903555:web:931cae91da94e5aaaa1f76',
    messagingSenderId: '275825903555',
    projectId: 'feepay-cf15d',
    authDomain: 'feepay-cf15d.firebaseapp.com',
    databaseURL: 'https://feepay-cf15d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feepay-cf15d.appspot.com',
    measurementId: 'G-SK3VNPV342',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyiyaTiCr4aXwf6BLvinK93KYGf1t51ro',
    appId: '1:275825903555:android:de35567356989988aa1f76',
    messagingSenderId: '275825903555',
    projectId: 'feepay-cf15d',
    databaseURL: 'https://feepay-cf15d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feepay-cf15d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKqlAGE905k8eaz5oE7CxZMEO2aEDW7c',
    appId: '1:275825903555:ios:61e733b1b6d54001aa1f76',
    messagingSenderId: '275825903555',
    projectId: 'feepay-cf15d',
    databaseURL: 'https://feepay-cf15d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feepay-cf15d.appspot.com',
    iosBundleId: 'com.jcdev.safedropPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYGpigGFsYh8hfUfQvSSCuE-lRQRGF_D0',
    appId: '1:275825903555:web:eec02b8d35f0b6d6aa1f76',
    messagingSenderId: '275825903555',
    projectId: 'feepay-cf15d',
    authDomain: 'feepay-cf15d.firebaseapp.com',
    databaseURL: 'https://feepay-cf15d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feepay-cf15d.appspot.com',
    measurementId: 'G-XGS6SY4N4T',
  );
}
